// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HasznaltAuto.API.Entities;

public partial class Car
{
    public int Id { get; set; }

    public int Price { get; set; }

    public string ProductionDate { get; set; }

    public int Mileage { get; set; }

    public int FuelTypeId { get; set; }

    public int CurrentOwner { get; set; }

    public bool IsDeleted { get; set; }

    public int? VehicleRegistrationId { get; set; }

    public int MakeId { get; set; }

    public int ModelId { get; set; }

    public virtual ICollection<CarHistory> CarHistories { get; set; } = new List<CarHistory>();

    public virtual User CurrentOwnerNavigation { get; set; }

    public virtual FuelType FuelType { get; set; }

    public virtual Make Make { get; set; }

    public virtual Model Model { get; set; }

    public virtual VehicleRegistration VehicleRegistration { get; set; }
}