// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HasznaltAuto.Entities;

public partial class CarHistory
{
    public int Id { get; set; }

    public int CarId { get; set; }

    public DateOnly SaleDate { get; set; }

    public decimal SalePrice { get; set; }

    public int SaleMileage { get; set; }

    public int PreviousOwnerId { get; set; }

    public virtual Car Car { get; set; }

    public virtual User PreviousOwner { get; set; }
}