// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HasznaltAuto.API.Entities;

public partial class HasznaltAutoDbContext : DbContext
{
    public HasznaltAutoDbContext(DbContextOptions<HasznaltAutoDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Car> Cars { get; set; }

    public virtual DbSet<CarHistory> CarHistories { get; set; }

    public virtual DbSet<FuelType> FuelTypes { get; set; }

    public virtual DbSet<LicensePlateType> LicensePlateTypes { get; set; }

    public virtual DbSet<Make> Makes { get; set; }

    public virtual DbSet<Model> Models { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VehicleRegistration> VehicleRegistrations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Car>(entity =>
        {
            entity.Property(e => e.ProductionDate)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.CurrentOwnerNavigation).WithMany(p => p.Cars)
                .HasForeignKey(d => d.CurrentOwner)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cars_Users");

            entity.HasOne(d => d.FuelType).WithMany(p => p.Cars)
                .HasForeignKey(d => d.FuelTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cars_FuelTypes");

            entity.HasOne(d => d.Make).WithMany(p => p.Cars)
                .HasForeignKey(d => d.MakeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cars_Makes");

            entity.HasOne(d => d.Model).WithMany(p => p.Cars)
                .HasForeignKey(d => d.ModelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cars_Models");

            entity.HasOne(d => d.VehicleRegistration).WithMany(p => p.Cars)
                .HasForeignKey(d => d.VehicleRegistrationId)
                .HasConstraintName("FK_Cars_VehicleRegistrations");
        });

        modelBuilder.Entity<CarHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CarHisto__3214EC07578A100B");

            entity.Property(e => e.SalePrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Car).WithMany(p => p.CarHistories)
                .HasForeignKey(d => d.CarId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarHistories_Cars");

            entity.HasOne(d => d.PreviousOwner).WithMany(p => p.CarHistories)
                .HasForeignKey(d => d.PreviousOwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarHistories_Users");
        });

        modelBuilder.Entity<FuelType>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<LicensePlateType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LicenseP__3214EC07428DB05E");

            entity.HasIndex(e => e.Name, "UQ__LicenseP__737584F63852EF84").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Make>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Makes__3214EC07652963EB");

            entity.HasIndex(e => e.Name, "UQ__Makes__737584F6137DF8C2").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Model>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Models__3214EC077681AEBE");

            entity.HasIndex(e => e.Name, "UQ__Models__737584F6CC9994F8").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC0742CB2154");

            entity.HasIndex(e => e.Name, "UQ__Roles__8A2B6160F7CB6AE6").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserRole",
                    r => r.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__UserRoles__RoleI__66603565"),
                    l => l.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__UserRoles__UserI__656C112C"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId").HasName("PK__UserRole__AF2760AD5CD204E5");
                        j.ToTable("UserRoles");
                    });
        });

        modelBuilder.Entity<VehicleRegistration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VehicleR__3214EC0722678C1D");

            entity.Property(e => e.LicensePlate).HasMaxLength(50);

            entity.HasOne(d => d.LicensePlateType).WithMany(p => p.VehicleRegistrations)
                .HasForeignKey(d => d.LicensePlateTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VehicleRe__Licen__75A278F5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}