// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HasznaltAuto.API.Entities;

public partial class LicensePlateType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<VehicleRegistration> VehicleRegistrations { get; set; } = new List<VehicleRegistration>();
}