// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HasznaltAuto.API.Entities;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public virtual ICollection<CarHistory> CarHistories { get; set; } = new List<CarHistory>();

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}