// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HasznaltAuto.Entities;

public partial class VehicleRegistration
{
    public int Id { get; set; }

    public string LicensePlate { get; set; }

    public int LicensePlateTypeId { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual LicensePlateType LicensePlateType { get; set; }
}